#!/usr/bin/python3
#
# Ubuntu installer for Kubernetes
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import argparse
import sys

try:
    option = sys.argv[1]
except IndexError:
    print("Unknown argument, please use `help` or `install`.")
    sys.exit(1)

if option not in ['help', 'install']:
    print(
        "Unknown argument: {}, please use `help` or `install`".format(option))
    sys.exit(1)

if option == 'help':
    print("This is the standard Ubuntu installer for Kubernetes that supports "
          "your workstation, vmware, openstack, AWS, Azure, Google, and Oracle "
          "cloud. Deploy a K8s instance with `kubernetes install`")
    sys.exit(0)
else:
    print("Fetching components..")
    sys.exit(0)
