#!/bin/sh

set -e

if $(snap list|grep -q 'microk8s'); then
    echo "The kubernetes package has been removed, however, microk8s"
    echo "is still installed and running on the system."
    echo ""
    echo "Please run 'sudo snap remove microk8s' to complete the "
    echo "uninstallation."
    echo ""
fi

if $(snap list|grep -q 'conjure-up'); then
    echo "The kubernetes package has been removed, however, conjure-up"
    echo "is still installed on the system."
    if $(juju models|grep -q 'conjure'); then
        echo ""
        echo "Additionally, conjure-up still has deployed juju controllers and models."
        echo "To clean those up, run 'juju destroy-model <model-name>' and"
        echo "'juju destroy-controller <controller-name>', then proceed to removing the"
        echo "conjure-up snap as shown below."
    fi
    echo ""
    echo "Please run 'sudo snap remove conjure-up' to complete the "
    echo "uninstallation."
    echo ""
fi

#DEBHELPER#
